const escapeJson = (value) => JSON.stringify(value).replaceAll('<', '\\u003c');

export function renderOwnerCommandCenter({ csrfToken }) {
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<meta name="owner-csrf" content="${csrfToken}"><title>AccessRevamp · Private Owner Command Center</title>
<style>
:root{color-scheme:dark;--ink:#0b0b0d;--panel:#151519;--line:#34343d;--cream:#f7f0df;--muted:#aaa6a0;--gold:#d6a02d;--coral:#ff5c4d;--ok:#78d99b}
*{box-sizing:border-box}body{margin:0;background:var(--ink);color:var(--cream);font:15px/1.55 Inter,Segoe UI,sans-serif}
button,textarea,select{font:inherit}.top{position:sticky;top:0;z-index:5;display:flex;justify-content:space-between;gap:20px;padding:18px 24px;border-bottom:1px solid var(--line);background:#0b0b0df2;backdrop-filter:blur(16px)}
.brand{font-weight:900;letter-spacing:-.03em}.brand i{color:var(--coral);font-style:normal}.secure{color:var(--ok);font-size:12px;text-transform:uppercase;letter-spacing:.14em}
.layout{display:grid;grid-template-columns:280px minmax(0,1fr);min-height:calc(100vh - 65px)}aside{border-right:1px solid var(--line);padding:22px;position:sticky;top:65px;height:calc(100vh - 65px);overflow:auto}
main{padding:28px;max-width:1500px;width:100%;margin:auto}.micro{color:var(--gold);font-size:11px;text-transform:uppercase;letter-spacing:.16em;font-weight:800}
h1{font-size:clamp(28px,5vw,60px);letter-spacing:-.055em;line-height:.95;margin:.25em 0}h2,h3,h4{line-height:1.1}.muted{color:var(--muted)}
.project{display:block;width:100%;text-align:left;border:1px solid var(--line);background:var(--panel);color:inherit;padding:14px;margin:8px 0;border-radius:12px;cursor:pointer}.project[aria-current=true]{border-color:var(--gold);box-shadow:inset 3px 0 var(--gold)}
.queue{display:grid;gap:24px}.card{border:1px solid var(--line);background:var(--panel);border-radius:18px;overflow:hidden}.card-head{display:flex;justify-content:space-between;gap:18px;padding:20px}
.status{display:inline-flex;border:1px solid var(--line);border-radius:99px;padding:5px 9px;font-size:11px;text-transform:uppercase;letter-spacing:.08em}.stage{background:#070708;min-height:420px;display:grid;place-items:center}
.stage img{display:block;max-width:100%;max-height:74vh;object-fit:contain}.stage p{color:var(--muted)}.details{display:grid;grid-template-columns:1fr 1fr;gap:20px;padding:20px}.details section{border:1px solid var(--line);padding:16px;border-radius:12px}
.critique{padding:20px;border-top:1px solid var(--line)}textarea{width:100%;min-height:110px;background:#09090b;color:var(--cream);border:1px solid var(--line);border-radius:10px;padding:12px}
.actions{display:flex;flex-wrap:wrap;gap:10px;margin-top:12px}button.action{border:0;border-radius:99px;padding:11px 16px;font-weight:800;cursor:pointer;background:var(--gold);color:#111}button.secondary{background:var(--cream)}button.delivery{background:var(--coral);color:white}button:disabled{opacity:.4;cursor:not-allowed}
.flash{position:fixed;right:20px;bottom:20px;max-width:420px;padding:14px 18px;background:var(--cream);color:#111;border-radius:12px;box-shadow:0 16px 60px #0008}.empty{padding:50px;border:1px dashed var(--line);border-radius:18px;text-align:center}
@media(max-width:800px){.layout{display:block}aside{position:static;height:auto;border-right:0;border-bottom:1px solid var(--line)}main{padding:18px}.details{grid-template-columns:1fr}.stage{min-height:260px}}
@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;animation:none!important;transition:none!important}}
</style></head><body><header class="top"><div class="brand">Access<i>Revamp</i> · Owner desk</div><div class="secure">● Local private session</div></header>
<div class="layout"><aside><span class="micro">Customer projects</span><div id="projects"></div><button class="project" id="refresh">Refresh queue</button></aside>
<main><span class="micro">Human approval boundary</span><h1>Creative decisions stay here.</h1><p class="muted">Critique routes to the assigned agent. Design approval never sends. Customer delivery requires its own explicit approval.</p><div id="queue" class="queue" aria-live="polite"></div></main></div>
<div id="flash" class="flash" hidden role="status"></div>
<script type="module">
const csrf=${escapeJson(csrfToken)};let data=null;let selected='';
const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const label=(s='')=>String(s).replace(/[_-]+/g,' ').replace(/\\b\\w/g,c=>c.toUpperCase());
const flash=(text)=>{const el=document.querySelector('#flash');el.textContent=text;el.hidden=false;setTimeout(()=>el.hidden=true,4500)};
async function api(payload){const r=await fetch('/api/review',{method:payload?'POST':'GET',headers:{...(payload?{'content-type':'application/json','x-owner-csrf':csrf}:{})},body:payload?JSON.stringify(payload):undefined});const j=await r.json();if(!r.ok)throw new Error(j.error||'Command failed');return j}
function projects(){const host=document.querySelector('#projects');host.innerHTML=(data.projects||[]).map(p=>'<button class="project" data-project="'+esc(p.id)+'" aria-current="'+(p.id===selected)+'"><strong>'+esc(p.name)+'</strong><br><span class="muted">'+esc(p.customer?.email||p.website_url||'Unlinked')+'</span></button>').join('')||'<p class="muted">No projects.</p>'}
function card(o){const p=data.projects.find(x=>x.id===o.project_id)||{};const notes=data.creativeFeedback.filter(x=>x.design_option_id===o.id);const events=data.creativeEvents.filter(x=>x.design_option_id===o.id);return '<article class="card"><div class="card-head"><div><span class="micro">'+esc(label(o.option_group))+' · Version '+(Number(o.revision_round)+1)+'</span><h2>'+esc(p.name||'Unknown project')+'</h2><a href="'+esc(p.website_url||'#')+'" target="_blank" rel="noreferrer">'+esc(p.website_url||'No website')+'</a></div><div><span class="status">'+esc(label(o.design_review_status))+'</span> <span class="status">'+esc(label(o.delivery_review_status))+'</span></div></div><div class="stage">'+(o.preview_url?'<img src="'+esc(o.preview_url)+'" alt="Creative review preview">':'<p>Preview unavailable. Delivery stays blocked.</p>')+'</div><div class="details"><section><h3>Source evidence</h3>'+(o.source_assets?.length?'<ul>'+o.source_assets.map(a=>'<li><strong>'+esc(label(a.asset_role))+'</strong> · '+esc(a.asset?.product_identifier||a.asset?.original_filename||'source')+' · '+esc((a.asset?.sha256||'').slice(0,12))+'</li>').join('')+'</ul>':'<p class="muted">No exact source assets linked.</p>')+'</section><section><h3>Version history</h3><p>Submitted by '+esc(o.submitted_by_agent||'unrecorded agent')+(o.parent_option_id?' as a revision.':'.')+'</p><p>'+esc(o.submission_note||o.prompt_summary||'No submission note.')+'</p><p>'+events.length+' durable review event(s).</p></section></div>'+(notes.length?'<div class="critique"><h3>Prior critique</h3>'+notes.map(n=>'<p><strong>'+esc(label(n.status))+':</strong> '+esc(n.note)+'</p>').join('')+'</div>':'')+'<form class="critique" data-option="'+esc(o.id)+'"><label><strong>Reply to the assigned agent</strong><textarea name="note" minlength="8" maxlength="4000" required placeholder="Name the exact change, why it matters, and what the next version must do."></textarea></label><div class="actions"><button class="action" name="request">Request changes</button><button class="action secondary" type="button" data-design="'+esc(o.id)+'">Approve design</button><button class="action delivery" type="button" data-delivery="'+esc(o.id)+'" '+(o.design_review_status==='approved'?'':'disabled')+'>Approve for customer delivery</button></div></form></article>'}
function render(){projects();const options=data.creativeOptions.filter(o=>!selected||o.project_id===selected);document.querySelector('#queue').innerHTML=options.map(card).join('')||'<div class="empty"><h2>No submitted designs</h2><p class="muted">Agent homepage, poster, Canva, and website versions appear here before any customer can receive them.</p></div>'}
async function load(){data=await api();if(!selected&&data.projects[0])selected=data.projects[0].id;render()}
document.addEventListener('click',async e=>{const project=e.target.closest('[data-project]');if(project){selected=project.dataset.project;render();return}if(e.target.id==='refresh'){await load();flash('Queue refreshed.');return}const design=e.target.closest('[data-design]');const delivery=e.target.closest('[data-delivery]');try{if(design){await api({action:'approve_creative_design',optionId:design.dataset.design});flash('Design approved. Customer delivery remains blocked.');await load()}if(delivery){if(!confirm('Approve this exact version for customer delivery? This is separate from design approval.'))return;await api({action:'approve_creative_delivery',optionId:delivery.dataset.delivery});flash('Delivery approval recorded.');await load()}}catch(err){flash(err.message)}});
document.addEventListener('submit',async e=>{const form=e.target.closest('[data-option]');if(!form)return;e.preventDefault();const note=new FormData(form).get('note');try{await api({action:'request_creative_changes',optionId:form.dataset.option,note,idempotencyKey:crypto.randomUUID()});flash('Critique routed to the assigned agent as a durable revision task.');await load()}catch(err){flash(err.message)}});
load().catch(err=>document.querySelector('#queue').innerHTML='<div class="empty"><h2>Command center unavailable</h2><p>'+esc(err.message)+'</p></div>');
</script></body></html>`;
}
