import '../cinematic-scroll.css';
import { icon } from '../components/icons.js';
import { shell } from '../components/shell.js';

export function cinematicPage() {
  const beats = [['signals','01 · Scattered signals','Your homepage speaks in fragments.','Passive observations begin as signals, not conclusions.','signal-field-01'],['evidence','02 · Verified evidence','Verification earns the redesign.','Source, observation, confidence, affected task, and human review turn a signal into usable evidence.','evidence-layers-01'],['hierarchy','03 · Redesigned hierarchy','The page learns what leads.','Offer, proof, and action arrive in an intentional order with accessible fallback states.','hierarchy-beacon-01'],['action','04 · Clear action','One next move resolves the story.','The visual system ends at a specific, honest conversion—not an endless effect.','action-path-01']];
  const markup = beats.map(([id,label,title,copy,image]) => `<article data-cinematic-beat="${id}"><picture><source srcset="/assets/generated/${image}.avif" type="image/avif"><source srcset="/assets/generated/${image}.webp" type="image/webp"><img src="/assets/generated/${image}.png" alt="" width="840" height="900" loading="lazy"></picture><div><span>${label}</span><h2>${title}</h2><p>${copy}</p>${id === 'action' ? `<a class="button button--sun" href="/pricing" data-nav>Get the $50 Homepage Reveal ${icon('arrow')}</a>` : ''}</div></article>`).join('');
  return shell(`<section class="cinematic-intro"><div class="container-wide"><span class="eyebrow">AccessRevamp cinematic evidence story</span><h1>From scattered signals to a clear action.</h1><p>Scroll through four connected beats. Every panel remains complete and readable when motion, JavaScript, or media is unavailable.</p><a class="button button--sun" href="#cinematic-stage">Enter the evidence story ${icon('arrow')}</a></div></section><section class="cinematic-stage" id="cinematic-stage" data-cinematic-stage><div class="cinematic-sticky"><div class="cinematic-beats">${markup}</div><div class="cinematic-progress" aria-hidden="true"><span data-cinematic-progress></span></div></div></section><section class="section cinematic-scope"><div class="container-wide page-hero__split"><div><span class="eyebrow">Bounded production</span><h2>Premium movement, with practical limits.</h2></div><div><p class="lede">One cohesive sequence, up to four story beats, one revision round, plus mobile, static, reduced-motion, and failed-media fallbacks.</p><a class="button" href="/pricing" data-nav>See the $250 plan ${icon('arrow')}</a></div></div></section>`, { pathname: '/cinematic-scroll', pageClass: 'cinematic-page' });
}
