import { plans, siteConfig } from '../config.js';
import { planCard } from '../components/cards.js';
import { shell } from '../components/shell.js';

const faq = (question, answer) => `<details><summary>${question}<span>+</span></summary><p>${answer}</p></details>`;

export function pricingPage() {
  const cards = Object.values(plans).map((plan) => planCard(plan, { featured: plan.key === 'complete_revamp' })).join('');
  return shell(`<section class="page-hero"><div class="container-wide page-hero__split"><div><span class="eyebrow">Four tiers · one-time prices</span><h1>Pick the depth. Keep the clarity.</h1></div><div class="page-hero__aside"><p class="lede">The approved list prices are exactly $0, $50, $200, and $250. Verified paid value is credited toward a higher tier; there is no recurring AccessRevamp platform fee.</p></div></div></section><section class="private-pricing-context" data-private-pricing-context hidden aria-live="polite"><div class="container-wide private-pricing-context__inner"><span class="eyebrow">Private pricing context</span><h2 data-private-customer></h2><p data-private-scope></p><p class="privacy-note" data-private-details hidden>Prepared for <a data-private-website target="_blank" rel="noopener noreferrer"></a>. Context expires <span data-private-expiry></span>; final scope still requires human confirmation.</p></div></section><section class="section"><div class="container-wide"><div class="pricing-grid">${cards}</div><div class="work-disclosure"><strong>${siteConfig.checkoutIsSandbox ? 'Test-mode notice' : 'Payment-mode notice'}</strong><span>${siteConfig.checkoutIsSandbox ? 'Paid checkout is configured for Stripe test mode and cannot create a live charge.' : 'The environment is marked for live payment but still requires separate launch approval.'} Taxes, when legally required, must be visible before payment.</span></div></div></section><section class="section"><div class="container-wide faq-layout"><div><span class="eyebrow">Scope questions</span><h2>Know what you are choosing.</h2></div><div class="faq-list">${faq('Does Homepage Reveal include implementation?', 'It includes the reviewed report and one landing-page direction. The deliverable states whether it is coded, conceptual, or both.')}${faq('Does Complete Website Revamp cover any size of website?', 'No. It covers up to five agreed standard content pages unless written scope says otherwise.')}${faq('How does upgrade credit work?', 'An authenticated customer sees server-verified, nonrefunded credit and the exact amount due for a higher tier.')}${faq('What is bounded in the cinematic service?', 'One narrative sequence, up to four story beats, one consolidated revision, and mobile plus reduced-motion fallbacks.')}${faq('Do you guarantee compliance, security, or sales?', 'No. The work provides practical design and passive or authorized observations, not legal certification, penetration testing, or business-outcome guarantees.')}</div></div></section>`, { pathname: '/pricing', pageClass: 'pricing-page' });
}
