import { plans, siteConfig } from '../config.js';
import { planCard } from '../components/cards.js';
import { shell } from '../components/shell.js';

const faq = (question, answer) => `<details><summary>${question}<span>+</span></summary><p>${answer}</p></details>`;

export function pricingPage() {
  const cards = Object.values(plans).map((plan) => planCard(plan, { featured: plan.key === 'quick_fix' })).join('');
  return shell(`<section class="page-hero"><div class="container-wide page-hero__split"><div><span class="eyebrow">Three plans · one-time prices</span><h1>Pick the depth. Keep the clarity.</h1></div><div class="page-hero__aside"><p class="lede">The approved catalog stays exact: $50, $199, and $250. There is no recurring AccessRevamp platform fee.</p></div></div></section><section class="section"><div class="container-wide"><div class="pricing-grid">${cards}</div><div class="work-disclosure"><strong>${siteConfig.checkoutIsSandbox ? 'Sandbox notice' : 'Checkout notice'}</strong><span>${siteConfig.checkoutIsSandbox ? 'Stripe is connected in test mode. These checkout actions do not create a live charge.' : 'Checkout is configured for live payment.'} Taxes, when legally required, must be visible before payment.</span></div></div></section><section class="section"><div class="container-wide faq-layout"><div><span class="eyebrow">Scope questions</span><h2>Know what you are choosing.</h2></div><div class="faq-list">${faq('Does Homepage Reveal include implementation?', 'No. It includes the reviewed report and completed homepage concept direction.')}${faq('Does Quick Fix cover any size of website?', 'It covers the agreed written scope. Page count, platform access, content, third-party tools, and timing are confirmed before work starts.')}${faq('What is bounded in the cinematic service?', 'One sequence, up to four story beats, one revision round, and mobile plus reduced-motion fallbacks.')}${faq('Do you guarantee compliance, security, or sales?', 'No. The work provides practical design and passive technical observations, not legal certification, penetration testing, or business-outcome guarantees.')}</div></div></section>`, { pathname: '/pricing' });
}
