import './styles/base.css';
import './styles/components.css';
import './styles/pages.css';
import './styles/auth.css';
import './styles/auth-otp.css';
import './styles/motion.css';
import './styles/image-led.css';
import './styles/studio-redesign.css';
import './styles/cinematic-renaissance.css';
import './styles/project-approval.css';
import './styles/order-wizard-dark-contrast.css';
import './styles/mobile.css';

import { createRouter } from './app/router.js';
import { updateDocumentMetadata } from './app/metadata.js';
import { icon } from './components/icons.js';
import { shell } from './components/shell.js';
import { homePage } from './pages/home.js';
import { setupHomeExperience } from './pages/home-interactions.js';
import { workDetailPage, workPage, setupWorkFilters } from './pages/work.js';
import { servicesPage } from './pages/services.js';
