begin;
update public.outreach_settings set sending_enabled=false where singleton=true;
create table if not exists public.free_snapshot_requests(id uuid primary key default gen_random_uuid(),request_id uuid not null unique,website_url text not null,contact_email text not null,business_context text not null,rate_key text not null,status text not null default 'pending' check(status in('pending','reviewing','completed','declined')),created_at timestamptz not null default now());
alter table public.free_snapshot_requests enable row level security;revoke all on public.free_snapshot_requests from anon,authenticated;
create or replace function public.submit_accessrevamp_snapshot(p_request_id uuid,p_website_url text,p_contact_email text,p_business_context text,p_rate_key text)returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$declare recent_count integer;begin if exists(select 1 from public.free_snapshot_requests where request_id=p_request_id)then return jsonb_build_object('status','duplicate');end if;select count(*)into recent_count from public.free_snapshot_requests where rate_key=p_rate_key and created_at>now()-interval'1 hour';if recent_count>=3 then raise exception'rate limit exceeded';end if;insert into public.free_snapshot_requests(request_id,website_url,contact_email,business_context,rate_key)values(p_request_id,left(p_website_url,2048),lower(left(p_contact_email,254)),left(p_business_context,1200),p_rate_key);return jsonb_build_object('status','accepted');end;$$;
revoke all on function public.submit_accessrevamp_snapshot(uuid,text,text,text,text)from public,anon,authenticated;grant execute on function public.submit_accessrevamp_snapshot(uuid,text,text,text,text)to service_role;

create table if not exists public.accessrevamp_operators(user_id uuid primary key references auth.users(id)on delete cascade,active boolean not null default true,created_at timestamptz not null default now());
alter table public.accessrevamp_operators enable row level security;revoke all on public.accessrevamp_operators from anon,authenticated;
create or replace function public.prevent_accessrevamp_audit_mutation()returns trigger language plpgsql as $$begin raise exception'audit records are append-only';end;$$;
drop trigger if exists accessrevamp_audit_immutable on public.accessrevamp_audit_log;create trigger accessrevamp_audit_immutable before update or delete on public.accessrevamp_audit_log for each row execute function public.prevent_accessrevamp_audit_mutation();

alter table public.prospects add column if not exists source_url text;alter table public.prospects add column if not exists observed_at timestamptz;alter table public.prospects add column if not exists observation text;alter table public.prospects add column if not exists evidence_strength text check(evidence_strength in('uncertain','moderate','strong'));alter table public.prospects add column if not exists confidence smallint check(confidence between 0 and 100);alter table public.prospects add column if not exists score smallint check(score between 0 and 100);alter table public.prospects add column if not exists human_reviewer uuid references auth.users(id);alter table public.prospects add column if not exists active_testing_authorized boolean not null default false;alter table public.prospects add column if not exists stage text not null default'researched' check(stage in('researched','evidence_ready','human_reviewed','preview_ready','approved','suppression_checked','queued','sent','stopped'));
create or replace function public.limit_accessrevamp_prospect_intake()returns trigger language plpgsql as $$begin if(select count(*)from public.prospects where created_at>=date_trunc('day',now()))>=20 then raise exception'daily research intake cap reached';end if;if new.stage not in('researched','evidence_ready')and coalesce(new.score,0)<70 then raise exception'score below 70 cannot advance';end if;return new;end;$$;
drop trigger if exists accessrevamp_prospect_intake_cap on public.prospects;create trigger accessrevamp_prospect_intake_cap before insert on public.prospects for each row execute function public.limit_accessrevamp_prospect_intake();

alter table public.previews add column if not exists revoked_at timestamptz;alter table public.previews add column if not exists approved_by uuid references auth.users(id);
create or replace function public.issue_accessrevamp_preview(p_prospect_id uuid,p_source_url text,p_concept_payload jsonb,p_expires_at timestamptz)returns text language plpgsql security definer set search_path=public,pg_temp as $$declare raw_token text;begin raw_token:=translate(trim(trailing'='from encode(gen_random_bytes(32),'base64')),'+/','-_');insert into public.previews(prospect_id,token_hash,source_url,concept_payload,status,expires_at)values(p_prospect_id,encode(digest(raw_token,'sha256'),'hex'),p_source_url,p_concept_payload,'draft',p_expires_at);return raw_token;end;$$;
revoke all on function public.issue_accessrevamp_preview(uuid,text,jsonb,timestamptz)from public,anon,authenticated;grant execute on function public.issue_accessrevamp_preview(uuid,text,jsonb,timestamptz)to service_role;

create table if not exists public.accessrevamp_outreach_queue(id uuid primary key default gen_random_uuid(),prospect_id uuid not null references public.prospects(id),recipient_email text not null,status text not null default'queued' check(status in('queued','canceled','stopped')),human_message_approved_by uuid not null references auth.users(id),follow_up_count smallint not null default 0 check(follow_up_count between 0 and 1),created_at timestamptz not null default now());
create unique index if not exists accessrevamp_outreach_one_active on public.accessrevamp_outreach_queue(prospect_id)where status='queued';alter table public.accessrevamp_outreach_queue enable row level security;revoke all on public.accessrevamp_outreach_queue from anon,authenticated;
create or replace function public.queue_accessrevamp_outreach(p_prospect_id uuid,p_operator_id uuid,p_reason text)returns uuid language plpgsql security definer set search_path=public,pg_temp as $$declare p public.prospects;queued_id uuid;begin if not exists(select 1 from public.accessrevamp_operators where user_id=p_operator_id and active)then raise exception'operator access required';end if;select * into p from public.prospects where id=p_prospect_id for update;if p.stage<>'suppression_checked'or p.human_reviewer is null then raise exception'ordered outreach prerequisites are incomplete';end if;if p.score<70 then raise exception'score below 70 cannot queue';end if;if exists(select 1 from public.suppression_list where lower(email)=lower(p.contact_email))then raise exception'recipient is suppressed';end if;if not exists(select 1 from public.previews where prospect_id=p.id and status='active'and human_approved_at is not null and expires_at>now())then raise exception'active approved preview required';end if;insert into public.accessrevamp_outreach_queue(prospect_id,recipient_email,human_message_approved_by)values(p.id,lower(p.contact_email),p_operator_id)returning id into queued_id;update public.prospects set stage='queued'where id=p.id;insert into public.accessrevamp_audit_log(actor_id,action,entity_type,entity_id,details)values(p_operator_id,'queue_approved','prospect',p.id::text,jsonb_build_object('reason',left(p_reason,500)));return queued_id;end;$$;
create or replace function public.stop_accessrevamp_outreach(p_email text,p_reason text,p_operator_id uuid default null)returns void language plpgsql security definer set search_path=public,pg_temp as $$begin insert into public.suppression_list(email,reason,source)values(lower(p_email),p_reason,'workflow')on conflict(email)do update set reason=excluded.reason,source=excluded.source;update public.accessrevamp_outreach_queue set status='stopped'where lower(recipient_email)=lower(p_email)and status='queued';update public.outreach_queue set status='canceled'where lower(recipient_email)=lower(p_email)and status in('draft','approved','queued','scheduled');update public.prospects set stage='stopped'where lower(contact_email)=lower(p_email);insert into public.accessrevamp_audit_log(actor_id,action,entity_type,entity_id,details)values(p_operator_id,'outreach_stopped','email',encode(digest(lower(p_email),'sha256'),'hex'),jsonb_build_object('reason',p_reason));end;$$;
revoke all on function public.queue_accessrevamp_outreach(uuid,uuid,text),public.stop_accessrevamp_outreach(text,text,uuid)from public,anon,authenticated;grant execute on function public.queue_accessrevamp_outreach(uuid,uuid,text),public.stop_accessrevamp_outreach(text,text,uuid)to service_role;
commit;
